# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/xiaomi/laurel_sprout/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/xiaomi/laurel_sprout/proprietary/bin/dpmd:system/product/bin/dpmd \
    vendor/xiaomi/laurel_sprout/proprietary/etc/dpm/dpm.conf:system/product/etc/dpm/dpm.conf \
    vendor/xiaomi/laurel_sprout/proprietary/etc/init/dpmd.rc:system/product/etc/init/dpmd.rc \
    vendor/xiaomi/laurel_sprout/proprietary/etc/permissions/com.qti.dpmframework.xml:system/product/etc/permissions/com.qti.dpmframework.xml \
    vendor/xiaomi/laurel_sprout/proprietary/etc/permissions/dpmapi.xml:system/product/etc/permissions/dpmapi.xml \
    vendor/xiaomi/laurel_sprout/proprietary/etc/permissions/cneapiclient.xml:system/product/etc/permissions/cneapiclient.xml \
    vendor/xiaomi/laurel_sprout/proprietary/etc/permissions/com.quicinc.cne.xml:system/product/etc/permissions/com.quicinc.cne.xml \
    vendor/xiaomi/laurel_sprout/proprietary/etc/permissions/com.qualcomm.qti.imscmservice-V2.0-java.xml:system/product/etc/permissions/com.qualcomm.qti.imscmservice-V2.0-java.xml \
    vendor/xiaomi/laurel_sprout/proprietary/etc/permissions/com.qualcomm.qti.imscmservice-V2.1-java.xml:system/product/etc/permissions/com.qualcomm.qti.imscmservice-V2.1-java.xml \
    vendor/xiaomi/laurel_sprout/proprietary/etc/permissions/telephony_product_privapp-permissions-qti.xml:system/product/etc/permissions/telephony_product_privapp-permissions-qti.xml \
    vendor/xiaomi/laurel_sprout/proprietary/etc/permissions/privapp-permissions-qti.xml:system/etc/permissions/privapp-permissions-qti.xml \
    vendor/xiaomi/laurel_sprout/proprietary/etc/permissions/qcrilhook.xml:system/product/etc/permissions/qcrilhook.xml \
    vendor/xiaomi/laurel_sprout/proprietary/etc/permissions/qti_libpermissions.xml:system/etc/permissions/qti_libpermissions.xml \
    vendor/xiaomi/laurel_sprout/proprietary/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    vendor/xiaomi/laurel_sprout/proprietary/etc/permissions/telephonyservice.xml:system/product/etc/permissions/telephonyservice.xml \
    vendor/xiaomi/laurel_sprout/proprietary/etc/sysconfig/qti_whitelist.xml:system/etc/sysconfig/qti_whitelist.xml \
    vendor/xiaomi/laurel_sprout/proprietary/framework/cneapiclient.jar:system/product/framework/cneapiclient.jar \
    vendor/xiaomi/laurel_sprout/proprietary/framework/com.quicinc.cne.jar:system/product/framework/com.quicinc.cne.jar \
    vendor/xiaomi/laurel_sprout/proprietary/framework/com.qualcomm.qti.imscmservice-V2.0-java.jar:system/product/framework/com.qualcomm.qti.imscmservice-V2.0-java \
    vendor/xiaomi/laurel_sprout/proprietary/framework/com.qualcomm.qti.imscmservice-V2.1-java.jar:system/product/framework/com.qualcomm.qti.imscmservice-V2.1-java \
    vendor/xiaomi/laurel_sprout/proprietary/framework/qti-telephony-common.jar:system/product/framework/qti-telephony-common.jar \
    vendor/xiaomi/laurel_sprout/proprietary/framework/QtiTelephonyServicelibrary.jar:system/product/framework/QtiTelephonyServicelibrary.jar \
    vendor/xiaomi/laurel_sprout/proprietary/framework/qcrilhook.jar:system/product/framework/qcrilhook.jar \
    vendor/xiaomi/laurel_sprout/proprietary/framework/com.qti.dpmframework.jar:system/product/framework/com.qti.dpmframework.jar \
    vendor/xiaomi/laurel_sprout/proprietary/framework/dpmapi.jar:system/product/framework/dpmapi.jar \
    vendor/xiaomi/laurel_sprout/proprietary/framework/tcmclient.jar:system/framework/tcmclient.jar \
    vendor/xiaomi/laurel_sprout/proprietary/lib/soundfx/libvolumelistener.so:system/lib/soundfx/libvolumelistener.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib/fm_helium.so:system/lib/fm_helium.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib/libfm-hci.so:system/lib/libfm-hci.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/soundfx/libvolumelistener.so:system/lib64/soundfx/libvolumelistener.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/com.qualcomm.qti.imscmservice@1.0.so:system/product/lib64/com.qualcomm.qti.imscmservice@1.0.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/com.qualcomm.qti.imscmservice@2.0.so:system/product/lib64/com.qualcomm.qti.imscmservice@2.0.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/com.qualcomm.qti.imscmservice@2.1.so:system/product/lib64/com.qualcomm.qti.imscmservice@2.1.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/com.qualcomm.qti.uceservice@2.0.so:system/product/lib64/com.qualcomm.qti.uceservice@2.0.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/com.quicinc.cne.server@1.0.so:system/product/lib64/com.quicinc.cne.server@1.0.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/com.qualcomm.qti.dpm.api@1.0.so:system/product/lib64/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/libdpmctmgr.so:system/product/lib64/libdpmctmgr.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/libdpmfdmgr.so:system/product/lib64/libdpmfdmgr.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/libdpmframework.so:system/product/lib64/libdpmframework.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/libdpmtcm.so:system/product/lib64/libdpmtcm.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/fm_helium.so:system/lib64/fm_helium.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/libfm-hci.so:system/lib64/libfm-hci.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/libdiag_system.so:system/lib64/libdiag_system.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/libimscamera_jni.so:system/product/lib64/libimscamera_jni.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/libimsmedia_jni.so:system/product/lib64/libimsmedia_jni.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/libmmrtpdecoder.so:system/lib64/libmmrtpdecoder.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/libmmrtpencoder.so:system/lib64/libmmrtpencoder.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/librcc.so:system/lib64/librcc.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/lib-imsvideocodec.so:system/product/lib64/lib-imsvideocodec.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/lib-imsvt.so:system/product/lib64/lib-imsvt.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/lib-imsvtextutils.so:system/product/lib64/lib-imsvtextutils.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/lib-imsvtutils.so:system/product/lib64/lib-imsvtutils.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/libsdm-disp-apis.so:system/product/lib64/libsdm-disp-apis.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/vendor.display.color@1.0.so:system/product/lib64/vendor.display.color@1.0.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/vendor.display.color@1.1.so:system/product/lib64/vendor.display.color@1.1.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/vendor.display.color@1.2.so:system/product/lib64/vendor.display.color@1.2.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/vendor.display.color@1.3.so:system/product/lib64/vendor.display.color@1.3.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/vendor.qti.hardware.data.latency@1.0.so:system/product/lib64/vendor.qti.hardware.data.latency@1.0.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/vendor.qti.latency@2.0.so:system/product/lib64/vendor.qti.latency@2.0.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/vendor.qti.ims.callinfo@1.0.so:system/product/lib64/vendor.qti.ims.callinfo@1.0.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/vendor.qti.ims.rcsconfig@1.0.so:system/product/lib64/vendor.qti.ims.rcsconfig@1.0.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/vendor.qti.imsrtpservice@1.0.so:system/product/lib64/vendor.qti.imsrtpservice@1.0.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/vendor.qti.hardware.radio.ims@1.0.so:system/product/lib64/vendor.qti.hardware.radio.ims@1.0.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/vendor.qti.hardware.radio.ims@1.1.so:system/product/lib64/vendor.qti.hardware.radio.ims@1.1.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/vendor.qti.hardware.radio.ims@1.2.so:system/product/lib64/vendor.qti.hardware.radio.ims@1.2.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/vendor.qti.hardware.radio.ims@1.3.so:system/product/lib64/vendor.qti.hardware.radio.ims@1.3.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/vendor.qti.hardware.radio.ims@1.4.so:system/product/lib64/vendor.qti.hardware.radio.ims@1.4.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/vendor.qti.hardware.iop@1.0.so:system/product/lib64/vendor.qti.hardware.iop@1.0.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/vendor.qti.hardware.iop@2.0.so:system/product/lib64/vendor.qti.hardware.iop@2.0.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/vendor.qti.hardware.perf@1.0.so:system/product/lib64/vendor.qti.hardware.perf@1.0.so \
    vendor/xiaomi/laurel_sprout/proprietary/lib64/vendor.xiaomi.hardware.displayfeature@1.0.so:system/lib64/vendor.xiaomi.hardware.displayfeature@1.0.so

PRODUCT_PACKAGES += \
    vendor.qti.hardware.fm@1.0 \
    CNEService \
    dpmserviceapp \
    ims \
    QtiTelephonyService \
    qcrilmsgtunnel \
    uceShimService
